name: ghoomo_pakistan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  otp_text_field: ^1.1.3
  firebase_core_platform_interface: 4.6.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  app_settings: ^4.2.0
  email_otp: ^2.0.1
  intl: ^0.17.0
  geolocator: ^9.0.2  #use to get current location
  flutter_spinkit:
  fluttertoast: ^8.0.9
  flutter_phone_direct_caller:
  carousel_slider:
  whatsapp_unilink:
  url_launcher:
  get:
  water_drop_nav_bar:
  quickalert:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Places/Punjab/Lahore/
    - assets/images/Places/Punjab/Faisalabad/
    - assets/images/Places/Punjab/Bahawalpur/
    - assets/images/Places/Punjab/Sheikhupura/
    - assets/images/Places/Punjab/Jhelum/

    - assets/images/Places/Sindh/Hyderabad/
    - assets/images/Places/Sindh/Jamshoro/
    - assets/images/Places/Sindh/Karachi/
    - assets/images/Places/Sindh/Kotri/
    - assets/images/Places/Sindh/Sukkur/

    - assets/images/Places/Khyber Pakhtunkhwa/Abbottabad/
    - assets/images/Places/Khyber Pakhtunkhwa/Naran/
    - assets/images/Places/Khyber Pakhtunkhwa/Shogran/
    - assets/images/Places/Khyber Pakhtunkhwa/Peshawar/
    - assets/images/Places/Khyber Pakhtunkhwa/Swat/

    - assets/images/Places/Gilgit Baltistan/

    - assets/images/Places/Islamabad/

    - assets/images/Places/Balochistan/Chaman/
    - assets/images/Places/Balochistan/Gwadar/
    - assets/images/Places/Balochistan/Quetta/
    - assets/images/Places/Balochistan/Sibi/
    - assets/images/Places/Balochistan/Ziarat/

    - assets/images/Places/Azad Jammu and Kashmir/
  fonts:
    - family: mainTextStyle
      fonts:
        - asset: assets/fonts/mainTextStyle.ttf
    - family: highlight
      fonts:
        - asset: assets/fonts/highlight.ttf
